Delete Account from Settings
Kanav-Arora/TravelBuddy pull request #105
Opened 2024-04-09 03:12 UTC by BautiSobenko

### Summary
In the Settings page, when the user clicks on the Delete modal button the account will be deleted.
  1.  Change user status to 'deleted'
  2.  Set Auth states to null
  3.  When user tries to sign-in again he will not be able to, an exception will be thrown, since the account will be logically deleted from database. 

### Tests
With postman I tested the different related endpoints, where all of them worked. 
  - Deleting the user (DELETE to the /account endpoint)
  - re-sign-in with the deleted user to verify the exception thrown
  - trying different fetchs to related endpoints like /account, /account:uid

2024-04-09 04:59 UTC, Kanav-Arora commented
Hi @BautiSobenko 
I'll review and merge this PR in sometime
Could you please raise a PR to postman fork also? for the new api you have created.

2024-04-09 18:10 UTC, Kanav-Arora requested changes

2024-04-09 18:10 UTC, Kanav-Arora commented on backend/controllers/user/create.controller.js
We can remove this as this is duplicate return statement

2024-04-09 18:10 UTC, Kanav-Arora commented on backend/controllers/userDetails/delete.controller.js
> +        console.error('Error updating user:', error);
instead of consoling lets do this
```
logger.error(error);

return res.status(500).send({ message: 'Internal Server Error :(' });
```

2024-04-09 18:11 UTC, Kanav-Arora commented
Hi @BautiSobenko 
Everything looks good
Please do these changes and also raise PR on postman

2024-04-09 18:17 UTC, BautiSobenko commented
> Hi @BautiSobenko Everything looks good Please do these changes and also raise PR on postman

Hi @Kanav-Arora 
Great. I'll be making the changes in a while. 👍

2024-04-10 05:22 UTC, Kanav-Arora commented
@BautiSobenko 
Please check if you are able to fork this
[<img src="https://run.pstmn.io/button.svg" alt="Run In Postman" style="width: 128px; height: 32px;">](https://app.getpostman.com/run-collection/16660574-9b5b8147-84e4-4aac-8e78-853919129baa?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D16660574-9b5b8147-84e4-4aac-8e78-853919129baa%26entityType%3Dcollection%26workspaceId%3D86bf64e4-7c93-462f-a269-716709f61a58)

2024-04-10 06:19 UTC, BautiSobenko commented
@Kanav-Arora 
Please tell me if you can review and merge the PR. I could fork sucessfully the collection, but when i make the change and try to raise the PR it shows me this warning. 
![image](https://github.com/Kanav-Arora/tripzip/assets/46655917/322aac08-c22d-48b9-91e1-ce80f7e54182)

2024-04-10 07:23 UTC, Kanav-Arora commented
Hi @BautiSobenko 
You fork is in private workspace you can move to public workspace by clicking on move collection and then creating a workspace name

2024-04-10 15:53 UTC, BautiSobenko commented
> Hi @BautiSobenko You fork is in private workspace you can move to public workspace by clicking on move collection and then creating a workspace name

That's the weird thing. I have the fork in a public new workspace that i've created and still throwing the same warning. I raised the pull request anyway

![image](https://github.com/Kanav-Arora/tripzip/assets/46655917/9e1779bc-6683-4c0a-a8d6-6b01ffbbec95)

2024-04-10 18:02 UTC, Kanav-Arora commented
Hi @BautiSobenko 
I'm unable to merge no issue I'll create the postman request. I'm reviewing your PR and lets merge it

2024-04-10 18:55 UTC, Kanav-Arora approved these changes

2024-04-10 18:55 UTC, merged

2024-04-10 19:02 UTC, Kanav-Arora commented
Thanks @BautiSobenko 
Great PR!