feat: fetch locations backend
Kanav-Arora/TravelBuddy pull request #113
Opened 2024-05-12 10:58 UTC by Aadi71

# Description

# How has this been tested?

- [ ] Test A
- [ ] Test B

# DB Migrations (Is the table being locked?)

# Affected Endpoint performances (Include the average endpoint load time)

# Post Deploy Tasks

# Screenshots:

# Task Link

# Self Review Checklist
- [ ] Deprecated code removed?
- [ ] Syntax & Formatting is correct
- [ ] Is the approach to the problem appropriate?
- [ ] Can anything be simplified?
- [ ] Are the naming conventions appropriate?
- [ ] Are there enough comments inline with the code?
- [ ] Documentation added?
- [ ] Arguments of method less than 6 ?
- [ ] Single responsibility functions
- [ ] Are the methods which can be reused added in common folders?

### Backend
- [ ] Are the methods lightweight (less than 20 lines)
- [ ] 2 step deploy needed(Migration, Jobs)
- [ ] Check if backward compatibility is needed
- [ ] Indexes are properly used for the queries?
- [ ] Caching implemented for frequent access data?
- [ ] For New table migrations, indices are added properly and reviewed by leads

### Frontend
- [ ] Colors and font-sizes according to theme file
- [ ] BEM used properly? Mixins used properly?
- [ ] Are the components lightweight(less than 200 lines)
- [ ] Tested responsive design on different devices

2024-05-12 11:44 UTC, Kanav-Arora requested changes

2024-05-12 11:44 UTC, Kanav-Arora commented on backend/controllers/locations/fetch.controller.js
> +        } = req.query;
No query check passed what if query is null

2024-05-12 11:44 UTC, Kanav-Arora commented on backend/controllers/locations/fetch.controller.js
> +        console.error('Error fetching locations:', error);
Use logger instead of consoling

2024-05-16 19:38 UTC, Aadi71 commented
Todo for me: Fetching the response from FE is bad, and saving the BE

2026-02-10 09:49 UTC, closed without merging